declare const __CAMPUS_REVIEW_API_BASE_URL__: string
declare const __CAMPUS_PRODUCTION_API_BASE_URL__: string
declare const __CAMPUS_WECHAT_APP_ID__: string
declare const __CAMPUS_APP_RELEASE__: string
