import { strict as assert } from 'node:assert'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const source = (path: string) => readFileSync(resolve(__dirname, path), 'utf8')
const appConfig = source('../src/app.config.ts')
const catalog = source('../src/pages/cat-atlas/index.tsx')
const list = source('../src/pages/cat-atlas/list.tsx')
const catalogList = source('../src/pages/cat-atlas/catalog-list.tsx')
const detail = source('../src/pages/cat-atlas/detail.tsx')
const detailFeed = source('../src/pages/cat-atlas/detail-feed.scss')
const report = source('../src/pages/cat-atlas/report.tsx')
const reportStyles = source('../src/pages/cat-atlas/catalog-report.scss')
const warmTheme = source('../src/pages/cat-atlas/warm-theme.scss')
const map = source('../src/pages/cat-atlas/map.tsx')
const api = source('../src/api/cat-atlas.ts')
const data = source('../src/features/cat-atlas/data.ts')

assert.match(appConfig, /root: 'pages\/cat-atlas'/u, '猫图鉴应注册为独立分包')
assert.match(appConfig, /'report', 'map'/u, '图鉴分包应注册出没地图')
assert.match(appConfig, /'index', 'list', 'detail'/u, '图鉴分包应注册独立列表页')
assert.match(catalog, /CatalogList/u, '猫咪图鉴首页应直接复用全部图鉴列表组件')
assert.doesNotMatch(catalog, /from '\.\/list'/u, '猫咪图鉴首页不应重新导出另一个页面模块')
assert.doesNotMatch(catalog, /cat-home-hero/u, '猫咪图鉴首页不应再渲染宣传型落地页')
assert.match(catalogList, /listCats/u, '全部图鉴应读取猫咪 API')
assert.match(catalogList, /useReachBottom/u, '全部图鉴应监听触底加载更多')
assert.match(catalogList, /PAGE_SIZE = 30/u, '全部图鉴应使用分页请求')
assert.match(catalogList, /setArea\(item\)/u, '全部图鉴应支持切换校区')
assert.match(catalogList, /changeSort/u, '全部图鉴应支持切换排序')
assert.match(catalogList, /cat-list-v2__load-more/u, '全部图鉴应显示加载更多状态')
assert.match(list, /CatalogList/u, '旧列表路由应复用普通列表组件')
assert.match(source('../src/pages/services/index.tsx'), /cat-atlas.*pages\/cat-atlas\/index/u, '服务入口应直接打开猫咪图鉴首页')
assert.doesNotMatch(appConfig, /pagePath: 'pages\/cat-atlas\//u, '猫猫图鉴不应注册为独立 Tab')
assert.match(catalogList, /cat-list-v2__card/u, '独立列表页应渲染猫咪卡片')
assert.match(detail, /我遇到它了/u, '详情页应提供目击打卡入口')
assert.match(detail, /getNavbarMetrics/u, '详情页沉浸式导航应读取胶囊适配指标')
assert.match(detail, /navigationBarHeight/u, '详情页操作按钮应与胶囊导航高度对齐')
assert.match(detail, /useCollapsingHeader/u, '详情页向上滚动应切换固定标题栏')
assert.match(detail, /title=\{cat\.name\}/u, '详情页吸顶导航应显示当前猫咪名称')
assert.match(detail, /immersive=\{!headerCollapsed\}/u, '详情页首屏应保持沉浸式导航')
assert.match(detail, /cat-detail-bottom__button--activity/u, '详情页应提供固定的最近动态按钮')
assert.match(detail, /cat-detail-bottom__button--report/u, '详情页应提供固定的目击按钮')
assert.doesNotMatch(detail, /ariaLabel='分享'/u, '详情页不应显示与微信胶囊重复的分享快捷按钮')
assert.doesNotMatch(detail, /出没地图|给它留言|cat-detail-live-preview--combined|cat-detail-shortcuts/u, '详情页不应展示已下线或重复入口')
assert.match(detailFeed, /\.cat-detail-bottom\s*\{[\s\S]*?position:\s*fixed/u, '详情页操作按钮应固定在初始视口底部')
assert.match(detailFeed, /\.cat-detail-hero__nav\s*\{[\s\S]*?position:\s*fixed/u, '详情页滚动时返回按钮应保持可见')
assert.match(report, /uploadMediaImage/u, '投稿页应提供照片上传、预览和重试')
assert.match(report, /submitCat/u, '投稿页应提交新猫审核')
assert.match(report, /Taro\.getLocation/u, '目击投稿页应优先获取当前位置')
assert.match(report, /Taro\.choosePoi/u, '目击投稿页应优先选择可读的 POI 地点')
assert.match(report, /report-location-primary/u, '目击投稿页应展示定位优先的地点入口')
assert.match(report, /locationSnapshot/u, '目击投稿页应展示定位返回的经纬度和精度')
assert.match(report, /customAreaActive/u, '投稿页选择其他地点后应进入自定义地点状态')
assert.match(report, /report-custom-area/u, '投稿页应展示自定义地点输入框')
assert.match(report, /CustomNavbar/u, '投稿页应复用统一自定义导航栏')
assert.match(report, /title=\{isNew \? '发现新猫' : '我遇到它了'\}/u, '投稿页顶部栏应展示当前投稿动作标题')
assert.match(report, /showBack/u, '投稿页顶部栏应提供固定返回入口')
assert.match(reportStyles, /我遇到了：用暖米白与杏橙强调相遇记录/u, '我遇到了页应使用暖色视觉主题')
assert.match(reportStyles, /\.report-page--sighting[\s\S]*?#fff8ed/u, '我遇到了页应使用暖米白背景')
assert.match(warmTheme, /\.cat-list-page[\s\S]*?#fbf5eb/u, '猫图鉴列表应使用暖米白背景')
assert.match(warmTheme, /\.cat-detail-page[\s\S]*?#f8f1e7/u, '猫咪详情应使用暖色背景')
assert.match(warmTheme, /\.cat-map-canvas[\s\S]*?#e8ead8/u, '出没地图应使用暖色地图底')
assert.match(warmTheme, /\.catalog-summary__track view[\s\S]*?#d88b47/u, '我的图鉴进度条应使用杏橙色')
assert.doesNotMatch(warmTheme, /#2b7aef|#2d8bd8|#2371ba|#f0f8ff|#e3f2fb/u, '猫图鉴暖色主题不应重新引入海蓝色')
assert.match(catalogList, /location-warm\.svg/u, '猫咪列表应使用暖色定位图标')
assert.match(map, /location-warm\.svg/u, '出没地图应使用暖色定位图标')
assert.match(map, /eye-warm\.svg/u, '出没地图应使用暖色动态图标')
assert.match(source('../src/pages/cat-atlas/sightings.tsx'), /location-warm\.svg/u, '最近动态应使用暖色定位图标')
assert.doesNotMatch(report, /useEffect/u, '目击投稿页不应进入页面后自动请求定位')
assert.match(appConfig, /scope\.userLocation/u, '小程序应声明定位用途说明')
assert.match(appConfig, /requiredPrivateInfos: \['choosePoi', 'getLocation'\]/u, '小程序应声明定位相关隐私接口')
assert.match(map, /区域级目击热点/u, '地图应明确保护精确位置')
assert.match(api, /\/api\/v1\/cats/u, '图鉴应定义后端 API 客户端')
assert.match(data, /name: '橘座'/u, '初始档案应包含橘座')

process.stdout.write('cat atlas smoke: ok\n')
