import { strict as assert } from 'node:assert'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { catPhotoHeightPercent } from '../src/features/cat-atlas/photo-layout'
import { mergeVisibleCats } from '../src/features/cat-atlas/return-refresh'

const visibleCats = [{ id: 1, count: 1 }, { id: 2, count: 2 }, { id: 3, count: 3 }]
const refreshedCats = [{ id: 2, count: 4 }, { id: 4, count: 1 }, { id: 1, count: 2 }]
assert.deepEqual(mergeVisibleCats(visibleCats, refreshedCats), [
  { id: 1, count: 2 }, { id: 2, count: 4 }, { id: 3, count: 3 },
], '返回刷新更新计数但保留已加载分页、顺序和缺失卡片')
assert.deepEqual(mergeVisibleCats(visibleCats, []), visibleCats, '空响应不得清空当前列表')
assert.deepEqual(mergeVisibleCats([], refreshedCats), [], '返回刷新不替代首次加载')

assert.equal(catPhotoHeightPercent(1600, 900), 56.25, '横图保留原比例')
assert.equal(catPhotoHeightPercent(800, 1000), 125, '4:5 竖图完整展示')
assert.equal(catPhotoHeightPercent(800, 2400), 125, '超长图高度限制为 4:5')
assert.equal(catPhotoHeightPercent(800, 800), 100, '方图完整展示')
assert.equal(catPhotoHeightPercent(0, 800), 75, '无效尺寸使用稳定占位')
assert.equal(catPhotoHeightPercent(NaN, 800), 75)

const source = (path: string) => readFileSync(resolve(__dirname, path), 'utf8')
const appConfig = source('../src/app.config.ts')
const catalog = source('../src/pages/cat-atlas/index.tsx')
const list = source('../src/pages/cat-atlas/list.tsx')
const catalogList = source('../src/pages/cat-atlas/catalog-list.tsx')
const returnRefresh = catalogList.split('const refreshVisible =')[1].split('const loadMore =')[0]
assert.doesNotMatch(returnRefresh, /setLoading\(|setPage\(|setHasMore\(|setError\(/u, '静默刷新不得卸载列表或重置分页')
assert.match(returnRefresh, /version !== requestVersion.current/u, '旧响应不得覆盖新筛选')
assert.match(returnRefresh, /currentPage <= lastPage/u, '刷新所有已加载页面而非只取第一页')
assert.match(catalogList, /if \(hasShownRef.current\) void refreshVisible\(\)/u)
const detail = source('../src/pages/cat-atlas/detail.tsx')
const atlasStyles = source('../src/pages/cat-atlas/atlas.scss')
const catalogStyles = source('../src/pages/cat-atlas/catalog.scss')
const report = source('../src/pages/cat-atlas/report.tsx')
const profileSuggestion = source('../src/pages/cat-atlas/profile-suggestion.tsx')
const profileSuggestionConfig = source('../src/pages/cat-atlas/profile-suggestion.config.ts')
const map = source('../src/pages/cat-atlas/map.tsx')
const api = source('../src/api/cat-atlas.ts')
const data = source('../src/features/cat-atlas/data.ts')

assert.match(appConfig, /root: 'pages\/cat-atlas'/u, '猫图鉴应注册为独立分包')
assert.match(appConfig, /'report', 'map'/u, '图鉴分包应注册出没地图')
assert.match(appConfig, /profile-suggestion/u, '图鉴分包应注册档案补充页')
assert.match(appConfig, /'index', 'list', 'detail'/u, '图鉴分包应注册独立列表页')
assert.match(catalog, /CatalogList/u, '猫咪图鉴首页应直接复用全部图鉴列表组件')
assert.doesNotMatch(catalog, /from '\.\/list'/u, '猫咪图鉴首页不应重新导出另一个页面模块')
assert.doesNotMatch(catalog, /cat-home-hero/u, '猫咪图鉴首页不应再渲染宣传型落地页')
assert.match(catalogList, /listCats/u, '全部图鉴应读取猫咪 API')
assert.doesNotMatch(catalogList, /setCatFavorite|cat-list-v2__heart/u, '列表不展示收藏入口或发起收藏请求')
assert.match(catalogList, /useReachBottom/u, '全部图鉴应监听触底加载更多')
assert.match(catalogList, /PAGE_SIZE = 30/u, '全部图鉴应使用分页请求')
assert.match(catalogList, /setArea\(item\)/u, '全部图鉴应支持切换校区')
assert.match(catalogList, /changeSort/u, '全部图鉴应支持切换排序')
assert.match(catalogList, /cat-journal__load-more/u, '全部图鉴应显示加载更多状态')
assert.match(list, /CatalogList/u, '旧列表路由应复用普通列表组件')
assert.match(source('../src/pages/services/index.tsx'), /cat-atlas.*pages\/cat-atlas\/index/u, '服务入口应直接打开猫咪图鉴首页')
assert.doesNotMatch(appConfig, /pagePath: 'pages\/cat-atlas\//u, '猫猫图鉴不应注册为独立 Tab')
assert.match(catalogList, /cat-journal__card/u, '独立列表页应渲染猫咪卡片')
assert.match(detail, /我遇到它了/u, '详情页应提供目击打卡入口')
assert.match(detail, /CustomNavbar/u, '详情页应复用统一导航以适配微信胶囊区')
assert.match(detail, /showBack/u, '详情页导航应始终提供返回入口')
assert.match(detail, /useCollapsingHeader/u, '详情页向上滚动应切换固定标题栏')
assert.match(detail, /<CustomNavbar title='猫咪档案'/u, '详情页导航应显示视觉稿的猫咪档案标题')
assert.match(detail, /immersive=\{!headerCollapsed\}/u, '详情页首屏应保持沉浸式导航')
assert.match(detail, /cat-detail-bottom__button--activity/u, '详情页应提供固定的最近动态按钮')
assert.match(detail, /cat-detail-bottom__button--report/u, '详情页应提供固定的目击按钮')
assert.match(detail, /cat-detail-live-preview__activity/u, '详情页最近动态应明确展示猫咪当时在做什么')
assert.match(detail, /cat-detail-live-preview__compose/u, '详情页最近动态应提供补充目击入口')
assert.match(detail, /profile-suggestion/u, '详情页基础档案应提供补充建议入口')
assert.match(profileSuggestion, /createCatProfileSuggestion/u, '档案补充页应提交待审核建议')
assert.match(profileSuggestion, /别名[\s\S]*性别[\s\S]*毛色[\s\S]*性格[\s\S]*常驻区域/u, '档案补充页应覆盖基础档案字段')
assert.match(profileSuggestionConfig, /navigationStyle: 'custom'/u, '档案补充页应使用自定义导航避免原生顶栏重叠')
const sightings = source('../src/pages/cat-atlas/sightings.tsx')
assert.match(sightings, /journal-card__activity/u, '动态列表应明确展示猫咪当时在做什么')
assert.match(sightings, /journal-summary__record/u, '动态列表应提供轻量补充目击入口')
assert.doesNotMatch(sightings, /journal-intro|journal-compose/u, '动态不再展示大宣传区和重复引导卡')
assert.match(sightings, /<CustomNavbar[\s\S]*?fixed/u, '动态列表应使用固定导航栏')
assert.match(sightings, /paddingTop: `\$\{navbarHeight \+ 14\}px`/u, '动态列表应按真实导航高度预留内容安全间距')
assert.doesNotMatch(detail, /ariaLabel='分享'/u, '详情页不应显示与微信胶囊重复的分享快捷按钮')
assert.doesNotMatch(detail, /ariaLabel='收藏'/u, '详情页封面不应显示遮挡图片的收藏快捷按钮')
assert.doesNotMatch(detail, /出没地图|给它留言|cat-detail-live-preview--combined|cat-detail-shortcuts/u, '详情页不应展示已下线或重复入口')
assert.match(report, /uploadMediaImage/u, '投稿页应提供照片上传、预览和重试')
assert.match(report, /submitCat/u, '投稿页应提交新猫审核')
assert.match(report, /Taro\.getLocation/u, '目击投稿页应优先获取当前位置')
assert.match(report, /Taro\.choosePoi/u, '目击投稿页应优先选择可读的 POI 地点')
assert.match(report, /cat-report__location-trigger/u, '投稿页应展示用户主动选择的地点入口')
assert.match(report, /cat-report__visual/u, '投稿应使用全宽照片主视觉')
assert.doesNotMatch(report, /cat-report__section-heading|cat-report__eyebrow/u, '投稿不应恢复重标题和逐字段分区卡')
assert.match(report, /locationSnapshot/u, '目击投稿页应展示定位返回的经纬度和精度')
assert.match(report, /customAreaActive/u, '投稿页选择其他地点后应进入自定义地点状态')
assert.match(report, /cat-report__custom-area/u, '投稿页应展示自定义地点输入框')
assert.match(report, /CustomNavbar/u, '投稿页应复用统一自定义导航栏')
assert.match(report, /title=\{isNew \? '发现新猫' : '我遇到它了'\}/u, '投稿页顶部栏应展示当前投稿动作标题')
assert.match(report, /showBack/u, '投稿页顶部栏应提供固定返回入口')
assert.match(catalogList, /cat-atlas\/figma\/location\.svg/u, '猫咪列表应使用 Figma 暖色定位图标')
assert.match(map, /location-warm\.svg/u, '出没地图应使用暖色定位图标')
assert.match(map, /eye-warm\.svg/u, '出没地图应使用暖色动态图标')
assert.match(source('../src/pages/cat-atlas/sightings.tsx'), /location-warm\.svg/u, '最近动态应使用暖色定位图标')
assert.doesNotMatch(report, /useEffect/u, '目击投稿页不应进入页面后自动请求定位')
assert.match(appConfig, /scope\.userLocation/u, '小程序应声明定位用途说明')
assert.match(appConfig, /requiredPrivateInfos: \['choosePoi', 'getLocation'\]/u, '小程序应声明定位相关隐私接口')
assert.match(map, /区域级目击热点/u, '地图应明确保护精确位置')
assert.match(api, /\/api\/v1\/cats/u, '图鉴应定义后端 API 客户端')
assert.match(data, /name: '橘座'/u, '初始档案应包含橘座')

assert.match(catalogStyles, /\.cat-journal__feed \{ display: flex; flex-direction: column/u, '列表应使用单列全图 Feed')
assert.match(catalogStyles, /\.cat-journal__photo[^}]*width: 100%/u, '照片必须使用全宽布局')
assert.match(catalogList, /import '\.\/catalog.scss'/u, '影集使用独立样式，隔离历史覆盖')
assert.doesNotMatch(catalogList, /cat-list-v2__column/u, '单列应按接口顺序直接渲染')
assert.match(atlasStyles, /cat-detail-bottom[^{}]*\{[^}]*position: fixed/u, '详情操作应固定在底部')
assert.match(atlasStyles, /safe-area-inset-bottom/u, '底部操作应适配安全区')
assert.match(atlasStyles, /prefers-reduced-motion/u, '应支持减少动画偏好')
for (const page of [detail, profileSuggestion, sightings]) {
  assert.match(page, /import '\.\/atlas.scss'/u, '各页面应使用同一套设计样式')
  assert.doesNotMatch(page, /warm-theme.scss|stitch\/list-1.jpg/u, '不应继续加载旧主题和兜底插画')
}
assert.match(report, /import '\.\/report-journal.scss'/u, '投稿应隔离旧表单覆盖')
assert.match(sightings, /import '\.\/sightings-journal.scss'/u, '动态应使用影集式样式')
assert.match(sightings, /useReachBottom/u, '动态应支持触底加载')
assert.match(sightings, /usePullDownRefresh/u, '动态应支持下拉刷新')
assert.match(sightings, /listCatSightings\(params.id, page.current \+ 1\)/u, '加载更多必须请求下一页')
assert.match(sightings, /Taro.previewImage/u, '动态照片应支持预览')
assert.match(sightings, /likeLocks.current.has/u, '点赞应防止并发重复操作')
assert.match(catalogList, /cover_url\?\.trim/u, '猫咪卡片应优先渲染真实照片')
assert.match(catalogList, /onError=\{onError\}/u, '真实照片加载失败时应切换为无图信息卡')
assert.match(catalogList, /cat-journal__card--text/u, '没有照片时应展示无图信息卡片')
assert.match(catalogList, /while \(visibleItems.length < 6/u, '分页应继续请求后续猫咪')
assert.match(report, /item.status === 'uploaded' && item.mediaId/u, '新猫必须上传成功才能提交')

process.stdout.write('cat atlas smoke: ok\n')
