import { strict as assert } from 'node:assert'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const source = (path: string) => readFileSync(resolve(__dirname, path), 'utf8')
const appConfig = source('../src/app.config.ts')
const catalog = source('../src/pages/cat-atlas/index.tsx')
const list = source('../src/pages/cat-atlas/list.tsx')
const catalogList = source('../src/pages/cat-atlas/catalog-list.tsx')
const detail = source('../src/pages/cat-atlas/detail.tsx')
const detailFeed = source('../src/pages/cat-atlas/detail-feed.scss')
const report = source('../src/pages/cat-atlas/report.tsx')
const map = source('../src/pages/cat-atlas/map.tsx')
const api = source('../src/api/cat-atlas.ts')
const data = source('../src/features/cat-atlas/data.ts')

assert.match(appConfig, /root: 'pages\/cat-atlas'/u, '猫图鉴应注册为独立分包')
assert.match(appConfig, /'report', 'map'/u, '图鉴分包应注册出没地图')
assert.match(appConfig, /'index', 'list', 'detail'/u, '图鉴分包应注册独立列表页')
assert.match(catalog, /CatalogList/u, '猫咪图鉴首页应直接复用全部图鉴列表组件')
assert.doesNotMatch(catalog, /from '\.\/list'/u, '猫咪图鉴首页不应重新导出另一个页面模块')
assert.doesNotMatch(catalog, /cat-home-hero/u, '猫咪图鉴首页不应再渲染宣传型落地页')
assert.match(catalogList, /listCats/u, '全部图鉴应读取猫咪 API')
assert.match(catalogList, /useReachBottom/u, '全部图鉴应监听触底加载更多')
assert.match(catalogList, /PAGE_SIZE = 30/u, '全部图鉴应使用分页请求')
assert.match(catalogList, /setArea\(item\)/u, '全部图鉴应支持切换校区')
assert.match(catalogList, /changeSort/u, '全部图鉴应支持切换排序')
assert.match(catalogList, /cat-list-v2__load-more/u, '全部图鉴应显示加载更多状态')
assert.match(list, /CatalogList/u, '旧列表路由应复用普通列表组件')
assert.match(source('../src/pages/services/index.tsx'), /cat-atlas.*pages\/cat-atlas\/index/u, '服务入口应直接打开猫咪图鉴首页')
assert.doesNotMatch(appConfig, /pagePath: 'pages\/cat-atlas\//u, '猫猫图鉴不应注册为独立 Tab')
assert.match(catalogList, /cat-list-v2__card/u, '独立列表页应渲染猫咪卡片')
assert.match(detail, /我遇到它了/u, '详情页应提供目击打卡入口')
assert.match(detail, /getNavbarMetrics/u, '详情页沉浸式导航应读取胶囊适配指标')
assert.match(detail, /navigationBarHeight/u, '详情页操作按钮应与胶囊导航高度对齐')
assert.match(detail, /cat-detail-shortcuts--single/u, '详情页只保留最近动态单入口')
assert.doesNotMatch(detail, /出没地图|给它留言/u, '详情页不应展示已下线的地图和留言入口')
assert.match(detailFeed, /\.cat-detail-hero__nav\s*\{[\s\S]*?position:\s*fixed/u, '详情页滚动时返回按钮应保持可见')
assert.match(report, /uploadMediaImage/u, '投稿页应提供照片上传、预览和重试')
assert.match(report, /submitCat/u, '投稿页应提交新猫审核')
assert.match(map, /区域级目击热点/u, '地图应明确保护精确位置')
assert.match(api, /\/api\/v1\/cats/u, '图鉴应定义后端 API 客户端')
assert.match(data, /name: '橘座'/u, '初始档案应包含橘座')

process.stdout.write('cat atlas smoke: ok\n')
